### PR TITLE
Feature/development developer field

### PR DESCRIPTION
**Pull request by james**
Use can now set a developer name on a development.

You can then search for that development using the developer name.

### CODE REVIEW

**Comment by james** [comment]
[Developer field for Development](https://trello.com/c/DGA0BLTk/89-developer-field-for-development)

**Comment by gazaston** [comment]
Should we be adding developer (and indeed development) names as columns in the table now?

**Review by gazaston — APPROVED** [review]
LGTM, [small comment here](https://github.com/dxw/affordable-housing-monitoring/pull/78#issuecomment-559575019) but not a blocker 👍

**Comment by james** [comment]
I don't know! I didn't want to just add them in incase it was too much info.

**Pull request merged**
